declare namespace NodeJS {
  interface ProcessEnv {
    REACT_APP_GET_NEWS_API_URL: string;
    REACT_APP_DEFAULT_NEWS_IMAGE: string;
    REACT_APP_DEFAULT_YOUTUBE_IMAGE: string;
    REACT_APP_NO_ARTICLE_MESSAGE: string;
    REACT_APP_GET_KEYWORDS_API_URL: string;
    REACT_APP_GET_YOUTUBE_API_URL: string;
    REACT_APP_EXTENSION_NOTICE: string;
    REACT_APP_NEWS_DEFAULT: string;
    REACT_APP_YOUTUBE_DEFAULT: string;
    REACT_APP_CONTENTS_DEFAULT: string;
    REACT_APP_MODAL_MESSAGE: string;
  }
}
